translate tutorial.md into Japanese
react-native-jp/react-native-website pull request #9
Opened 2021-02-10 14:26 UTC by Kotlia

## 気になる点

- スタイリングの説明 (44行目あたり)
- Containerの訳としてコンテナは適切か？
- props: 特に日本語訳を思いつかなかったのでそのまま。カタカナ表記のほうが好ましい？

どこまで意訳するかに迷いました。気になる点はコメントお願いします～

2021-02-12 03:41 UTC, Naturalclar commented on docs/tutorial.md
> +次に `HelloWorldApp` 関数があります。これは [関数コンポーネント](https://reactjs.org/docs/components-and-props.html#function-and-class-components) と呼ばれ、Web上のReactと同じように動作します。この関数は、いくつかのスタイルを持つ `View` コンポーネントとその子要素としての `Te
リンク先のドキュメントも日本語版にしたらより良さそう
```suggestion
次に `HelloWorldApp` 関数があります。これは [関数コンポーネント](https://ja.reactjs.org/docs/components-and-props.html#function-and-class-components) と呼ばれ、Web上のReactと同じように動作します。この関数は、いくつかのスタイルを持つ `View` コンポーネントとその子要素としての `Text` を返却します。
```

2021-02-12 03:43 UTC, Naturalclar commented on docs/tutorial.md
> +いくつかJavaScriptとは思えない文法があったかもしれません。パニックにならないで下さい、_これは未来です_。
「パニックにならないでください」は「大丈夫です」の方がすっきりするかもと思いました。
「これは未来です」も若干違和感を覚えたので変更を提案してみましたがどうでしょう？
```suggestion
いくつか JavaScript とは思えない文法があったかもしれません。大丈夫です、_これが最先端です_。
```

2021-02-12 03:44 UTC, Naturalclar commented on docs/tutorial.md
> +## Porps
```suggestion
## Props
```

2021-02-12 03:52 UTC, Naturalclar commented on docs/tutorial.md
> +React NativeはReactに似ていますが、ネイティブコンポーネントをウェブコンポーネントの代わりに使用します。つまり、React Nativeの基礎を理解する為には、Reactの知識 (JSX, コンポーネント、`state`, `props` 等)が必須になります。もし既にReactの知識を持っていたとしても、ネイティブコンポーネント等、React Native独自の仕様を学ぶ必要が
読みやすさ重視のために、半角と全角の文字の間にはスペースを入れたいです！
```suggestion
React Native は React に似ていますが、ネイティブコンポーネントをウェブコンポーネントの代わりに使用します。つまり、React Native の基礎を理解する為には、React の知識 (JSX, コンポーネント、`state`, `props` 等)が必須になります。もし既に React の知識を持っていたとしても、ネイティブコンポーネント等、React Native 独自の仕様を学ぶ必要があります。このチュートリアルは React の予備知識を問わず、全ての方を対象としています。
```

2021-02-12 03:52 UTC, Naturalclar requested changes
@Kotlia ありがとうございます！いくつかコメントしたので、確認いただけると助かります

2021-02-12 11:15 UTC, Kotlia commented
全て修正させていただきました。Reviewありがとうございました～

2021-02-14 04:29 UTC, Naturalclar commented on docs/tutorial.md
> +あなたが作ったコンポーネントを `props` 使用することが可能です。`props` はコンポーネントを一般化し、色々な場所で少しづつ違ったプロパティを持つことができます。関数コンポーネントの場合は`props.{NAME}`、クラスコンポーネントの場合は `this.props.{NAME}` でアクセスできます。例：
原文と行数をあわせるために改行を追加します
```suggestion

あなたが作ったコンポーネントを `props` 使用することが可能です。`props` はコンポーネントを一般化し、色々な場所で少しづつ違ったプロパティを持つことができます。関数コンポーネントの場合は`props.{NAME}`、クラスコンポーネントの場合は `this.props.{NAME}` でアクセスできます。例：
```

2021-02-14 04:30 UTC, Naturalclar approved these changes
@Kotlia ありがとうございます！LGTMです！

2021-02-14 04:30 UTC, merged